const router=require('express').Router();
const ctrl=require('./users.controller');
const auth=require('../../middleware/authenticate');
const ts=require('../../middleware/tenantScope');
const authz=require('../../middleware/authorize');
const validate=require('../../middleware/validate');
const { z }=require('zod');
const createSchema=z.object({ email:z.string().email(), password:z.string().min(8), first_name:z.string().min(1), last_name:z.string().min(1), role_id:z.string().uuid() });
const updateSchema=z.object({ first_name:z.string().optional(), last_name:z.string().optional(), role_id:z.string().uuid().optional(), language:z.enum(['en','ar']).optional() });
const resetSchema =z.object({ password:z.string().min(8).regex(/[A-Z]/).regex(/[0-9]/) });
router.use(auth,ts);
router.get   ('/',                    authz('users:view'),   ctrl.list);
router.post  ('/',                    authz('users:manage'), validate(createSchema),       ctrl.create);
router.get   ('/:id',                 authz('users:view'),   ctrl.getById);
router.put   ('/:id',                 authz('users:manage'), validate(updateSchema),       ctrl.update);
router.post  ('/:id/deactivate',      authz('users:manage'), ctrl.deactivate);
router.post  ('/:id/activate',        authz('users:manage'), ctrl.activate);
router.post  ('/:id/reset-password',  authz('users:manage'), validate(resetSchema), ctrl.resetPassword);
module.exports=router;
